services:
  app:
    image: nacento/webume:0.3-experimental
    container_name: nginx-alpine
    ports:
      - "8886:8886"
      - "80"
    volumes:
      - appdata:/var/www
      - ./src:/var/www/html:cached
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - sockdata:/sock
      # - ssldata:/etc/nginx/certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/Andorra
    depends_on:
      - phpfpm

  phpfpm:
    image: markoshust/magento-php:8.3-fpm-4
    container_name: php-fpm
    ports:
      - "9000"
    env_file: env/phpfpm.env
    volumes:
      - appdata:/var/www
      - ./src:/var/www/html:cached
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - sockdata:/sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/Andorra
    depends_on:
      - db
      - redis
      - opensearch
      - rabbitmq

  supervisor:
    image: nacento/supervisor-php8.3-fpm:0.2-experimental
    container_name: supervisor
    ports:
      - "9000"
    env_file: env/phpfpm.env
    volumes:
      - appdata:/var/www
      - ./src:/var/www/html:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ./mountConf/supervisor/conf.d/cron.conf:/etc/supervisor/conf.d/cron.conf:ro
      - sockdata:/sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      CONSUMERS: >
        async.operations.all,
        product_action_attribute.update,
        product_action_attribute.website.update
      PHP_MEMORY_LIMIT: 1024M
      MAX_MESSAGES: 500
      RUN_AS_USER: app
      WORKDIR: /var/www/html
      TZ: Europe/Andorra
    depends_on:
      - phpfpm

  db:
    image: mariadb:11.4
    container_name: mariadb
    command:
      - --max_allowed_packet=64M
      - --optimizer_use_condition_selectivity=1
      - --optimizer_switch=rowid_filter=off
      - --log_bin_trust_function_creators=1
    ports:
      - "3306:3306"
    env_file: env/db.env
    environment:
      - TZ=Europe/Andorra
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: valkey/valkey:8.1-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    environment:
      - TZ=Europe/Andorra

  opensearch:
    image: markoshust/magento-opensearch:2.12-0
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600"
      - "9650"
    env_file: env/opensearch.env
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - index.blocks.read_only_allow_delete
      - TZ=Europe/Andorra

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671"
      - "15691"
      - "15692"
      - "25672"
      - "4369"
      - "5671"
      - "5672"
    env_file: env/rabbitmq.env
    environment:
      - TZ=Europe/Andorra
      - RABBITMQ_NODENAME=rabbit@rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  mailcatcher:
    image: sj26/mailcatcher:v0.10.0
    container_name: emailer
    ports:
      - "1080:1080"
      - "1025"
    environment:
      - TZ=Europe/Andorra

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: minio
    restart: unless-stopped
    # entrypoint: '/bin/sh -c "mkdir -p /data/archive /data/catalog /data/jobs /data/category && minio server --console-address :9001 /data"'
    command: server /data --console-address ":9001"
    env_file: env/minio.env
    environment:
      TZ: Europe/Andorra
    volumes:
      - /mnt/miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  dbdata:
  rabbitmqdata:
  sockdata:
  # ssldata:
  redisdata:
  appdata:
